# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: svogrig <svogrig@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/28 19:17:42 by svogrig           #+#    #+#              #
#    Updated: 2025/02/01 21:00:37 by svogrig          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:=	phonebook
SRC 	:=	main.cpp \
			Contact.cpp \
			PhoneBook.cpp \
			clean_input.cpp

include ../ex00/Makefile
